### ISSUE TITLE
How to use this SDK?

### ISSUE THREAD

**Issue by ROCHatty** [blesta/pterodactyl-sdk#2]
Hi,,

I have a question on how to use this SDK.
Should I use it like this?
`$pterodactyl = new \Blesta\PterodactylSDK\PterodactylApi("API_KEY", "BASE_URL");`

Thank you,,

**Comment by JReissmueller** [comment]
Oh hey, sorry about this, didn't add a note to this repository like I did to the pterodactyl module repository.  This is still under development.  I'll try and push an update some time today.  That being said, yea however you want to access the class (through namespace or a use statement) it would look something like that.  Then to execute a particular action it would be:
`$response = $pterodactyl->Requestor->action($arg1, $arg2, ...);`

**Comment by JReissmueller** [comment]
I've created a readme, hopefully it is helpful :)

**Comment by ROCHatty** [comment]
Thank you!

**Comment by ROCHatty** [comment]
Hi,
I just tried the following code:
`require 'vendor/autoload.php';
$api = new \Blesta\PterodactylSDK\PterodactylApi('KEY_HERE', 'http://URL_HERE:666', false);
$locationResponse = $api->Servers->getAll();
echo $locationResponse->response();`

I got a http error 500 (So something wrong with the code?)
Thanks!

**Comment by ROCHatty** [comment]
When I removed
` $api = new \Blesta\PterodactylSDK\PterodactylApi('KEY_HERE', 'http://URL_HERE:666', false);` (and the lines after) it didn't give me an error 500 anymore.

**Comment by JReissmueller** [comment]
Okay, go ahead and update to the new 0.2 branch.  I think the autoloading should work now.
